---
# Job to run Outline database migrations before starting the main deployment
apiVersion: batch/v1
kind: Job
metadata:
  name: outline-migrations
  namespace: outline
  labels:
    app: outline
    component: migrations
spec:
  template:
    metadata:
      labels:
        app: outline
        component: migrations
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-db
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          until nc -z postgresql.outline.svc 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL is ready"
          sleep 5
      containers:
      - name: migrations
        image: outlinewiki/outline:0.83.0
        command:
        - sh
        - -c
        - |
          echo "Running Outline database migrations..."
          yarn sequelize:migrate || echo "Migrations completed or already applied"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: database-url
        - name: PGSSLMODE
          value: "disable"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

