apiVersion: v1
items:
- apiVersion: v1
  data:
    SECRET_KEY: ZjBkYjI1ODY4MzcyYzBlMDA4MzhmOTU4YWNmNTFiOWE5NzE2NzI2OWZkZjI3ZGFkNDU2MzllN2Y5ZGIzYTJjZg==
    UTILS_SECRET: MDcwNDU1NzRjZGYxYzFkOWYwOGEwYWRkODk0YjQ3YmYxYWIzMzJjZGJhYjJmOTFlN2IyODI5YTg4ZWY1MjY4YQ==
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"SECRET_KEY":"ZjBkYjI1ODY4MzcyYzBlMDA4MzhmOTU4YWNmNTFiOWE5NzE2NzI2OWZkZjI3ZGFkNDU2MzllN2Y5ZGIzYTJjZg==","UTILS_SECRET":"MDcwNDU1NzRjZGYxYzFkOWYwOGEwYWRkODk0YjQ3YmYxYWIzMzJjZGJhYjJmOTFlN2IyODI5YTg4ZWY1MjY4YQ=="},"kind":"Secret","metadata":{"annotations":{},"creationTimestamp":null,"name":"outline-config","namespace":"outline"}}
    creationTimestamp: "2025-11-14T02:34:12Z"
    name: outline-config
    namespace: outline
    resourceVersion: "6024207"
    uid: fd3a3424-0383-48da-92e1-cc316d0d9e06
  type: Opaque
- apiVersion: v1
  data:
    client-secret: T1JuSU0weEc4Wk5NYmgzMmFLaVlqTUc3ak84QWZRU1k=
  kind: Secret
  metadata:
    creationTimestamp: "2025-11-14T04:04:29Z"
    name: outline-oidc
    namespace: outline
    resourceVersion: "6041975"
    uid: 52edf33e-870e-42b0-98c9-1f38ce351863
  type: Opaque
- apiVersion: v1
  data:
    database-url: cG9zdGdyZXM6Ly9vdXRsaW5lOkxGT252QndPQ2RWUDB3ZG5hNVl2d1BzbVdPWk11Wm45QHBvc3RncmVzcWwub3V0bGluZS5zdmM6NTQzMi9vdXRsaW5lP3NzbG1vZGU9ZGlzYWJsZQ==
    password: TEZPbnZCd09DZFZQMHdkbmE1WXZ3UHNtV09aTXVabjk=
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"database-url":"cG9zdGdyZXM6Ly9vdXRsaW5lOkxGT252QndPQ2RWUDB3ZG5hNVl2d1BzbVdPWk11Wm45QHBvc3RncmVzcWwub3V0bGluZS5zdmM6NTQzMi9vdXRsaW5lP3NzbG1vZGU9ZGlzYWJsZQ==","password":"TEZPbnZCd09DZFZQMHdkbmE1WXZ3UHNtV09aTXVabjk="},"kind":"Secret","metadata":{"annotations":{},"creationTimestamp":null,"name":"postgresql-credentials","namespace":"outline"}}
    creationTimestamp: "2025-11-14T02:34:12Z"
    name: postgresql-credentials
    namespace: outline
    resourceVersion: "6024202"
    uid: fa106981-30e7-4271-a389-e3272cdad247
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
